name: Python CI

on:
  push:
  pull_request:

jobs:
  run-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.x']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi

      - name: Run Python
        run: |
          python --version
          # replace with the command you want to run, e.g. tests or a script:
          if [ -f main.py ]; then
            python main.py
          else
            echo "No main.py found — replace this step with your desired command (pytest, script, etc.)"
          fi